classes:
  veh:
    name: Car
    giou_asso: 1.5
    giou_redund: 0.45
    max_age: 3
    min_hits: 3
    score_thr: 0.47
    nms_th: 0.35
    post_nms_iou: 0.7
    measurement_noise: [1.0, 1.0, 0.4,0.4, 1.0, 1.0, 0.1]

  cyc:
    name: Cyclist
    giou_asso: 1.2
    giou_redund: 0.6
    max_age: 5
    min_hits: 3
    score_thr: 0.40
    nms_th: 0.5
    post_nms_iou: 0.5
    measurement_noise: [0.22, 0.22, 0.45, 0.06, 0.55, 0.55, 0.35]

  ped:
    name: Pedestrian
    giou_asso: 1.3
    giou_redund: 0.2
    max_age: 6
    min_hits: 3
    score_thr: 0.35
    nms_th: 0.5
    post_nms_iou: 0.5
    measurement_noise: [0.25, 0.25, 0.5, 0.08, 0.6, 0.6, 0.4]
